FROM python:3.11-slim
WORKDIR /app

# Install dependencies
RUN pip install --no-cache-dir mcp-server-qdrant

# Expose port
EXPOSE 8000

# Set environment variables
ENV QDRANT_URL=":memory:"
ENV COLLECTION_NAME="test-collection"
ENV FASTMCP_PORT=8000
ENV FASTMCP_HOST=0.0.0.0

# Start command
CMD ["python", "-m", "mcp_server_qdrant", "--transport", "sse"]
